INSERT INTO TopicCategories VALUES (nextval('topiccategories_category_id_seq'), 'Arts', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Automotive & Vehicle', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Business & Industrial', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Careers', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Comedy', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Education', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Entertainment', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Family & Parenting', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Fiction', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Finance', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Government', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Health & Fitness', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'History', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Hobbies & Interest', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Home & Garden', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Music', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'News', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Pets', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Politics', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Religion & Spirituality', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Science', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Society & Culture', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Sports', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Style & Fashion', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Technology', now(), now());
INSERT INTO TopicCategories VALUES (nextval('TopicCategories_category_id_seq'), 'Travel', now(), now());

-- Insertion of Languages master records

INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'English' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Hindi' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Malayalam' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Tamil' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Kannada' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Telugu' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Urdu' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Konkani' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Bengali' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Gujarati' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Assamese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Marathi' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Punjabi' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Sanskrit' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Bhojpuri' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Bodo' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Dogri' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Kashmiri' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Maithili' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Manipuri' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Odia' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Santali' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Sindhi' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Nepali' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Arabic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'German' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'French' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Afrikaans' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Albanian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Algerian Arabic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Amharic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Basque' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Belarusian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Bulgarian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Burmese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Catalan' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Croatian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Czech' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Danish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Dutch' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Egyptian Arabic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Estonian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Faeroese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Farsi' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Finnish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Gaelic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Gan Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'German' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Greek' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Hakka Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Hausa' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Hebrew' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Hungarian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Icelandic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Igbo' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Indonesian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Iranian Persian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Irish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Italian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Japanese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Javanese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Jin Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Korean' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Kurdish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Latvian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Lithuanian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Macedonian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Magahi' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Malaysian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Maltese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Mandarin Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Min Nan Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Moroccan Arabic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'North Levantine Arabic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Northern Uzbek' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Norwegian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Pashto' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Polish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Portuguese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Rhaeto-Romanic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Romanian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Russian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Serbian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Slovak' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Slovenian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Sorbian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Spanish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Sudanese Arabic' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Sunda' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Swedish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Tagalog' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Thai' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Tsonga' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Tswana' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Turkish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Ukrainian' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Venda' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Vietnamese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Welsh' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Wu Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Xhosa' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Xiang Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Yiddish' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Yoruba' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Yue Chinese' , now(), now());
INSERT INTO Languages VALUES (nextval('languages_language_id_seq'), 'Zulu' , now(), now());

